### ISSUE TITLE
50% launch rate from the shell script, __init__() exactly 4 arguments, 3 given

### ISSUE THREAD

**Issue by SteveMacenski** [SteveMacenski/cyton_gamma_300-1500_operation_and_simulation#5]
error as above happens significantly more frequently in the xterm windows opened by the shell script. Determine root cause and fix.

**Comment by SteveMacenski** [comment]
full tracebok 

`[ERROR] [WallTime: 1483459458.334498] Error processing request: __init__() takes exactly 4 arguments (3 given)
['Traceback (most recent call last):\n', '  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 623, in _handle_request\n    response = convert_return_to_response(self.handler(request), self.response_class)\n', '  File "/home/rdtintern/catkin_ws/src/dynamixel_motor-master/dynamixel_controllers/nodes/controller_manager.py", line 224, in start_controller\n    self.check_deps()\n', '  File "/home/rdtintern/catkin_ws/src/dynamixel_motor-master/dynamixel_controllers/nodes/controller_manager.py", line 181, in check_deps\n    controller = kls(controller_name, dependencies)\n', 'TypeError: __init__() takes exactly 4 arguments (3 given)\n']
`

**Comment by WeiJunQ** [comment]
What should I do if this problems happen? Could you give me some advice?

**Comment by Dhrams** [comment]
I don't know who else is still using something like this besides me, but the answer to this problem is just to write self into kls(controller_name, dependencies), like so:

controller = kls(self, controller_name, dependencies).
